=== oscarbravovillada/XMLyDTD/UD. Activitats XML DTS/ejercicio1.dtd
<!ELEMENT listaventas (venta*)>
<!ELEMENT venta (importe, fecha, venedor , comprador, codFac)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT venedor (#PCDATA)>
<!ELEMENT comprador (#PCDATA)>
<!ELEMENT codFac (#PCDATA)>

=== oscarbravovillada/XMLyDTD/UD. Activitats XML DTS/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaventas SYSTEM "ejercicio1.dtd" >
<listaventas>
	<venta>
		<importe>1500</importe>
		<fecha>2024-06-15</fecha>
		<venedor>Juan Pérez</venedor>
		<comprador>Empresa XYZ</comprador>
		<codFac>F20240615-001</codFac>
	</venta>
	<venta>
		<importe>1500</importe>
		<fecha>2024-06-15</fecha>
		<venedor>Juan Pérez</venedor>
		<comprador>Empresa XYZ</comprador>
		<codFac>F20240615-001</codFac>
	</venta>
	<venta>
		<importe>1500</importe>
		<fecha>2024-06-15</fecha>
		<venedor>Juan Pérez</venedor>
		<comprador>Empresa XYZ</comprador>
		<codFac>F20240615-001</codFac>
	</venta>
</listaventas>
